# Site settings
title: Shiftmates Blog
header-img: img/home-bg.jpg
email: hello@shiftmates.net
description: "Give and get extra hours at work with coworkers. Shiftmates connects employees to simplify shift trading!"
baseurl: "/"
url: "http://shiftmates.net"
twitter_username: shiftmates
github_username:  ch4
facebook_username:  harveyharveyharvey

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate_path: "/blog/page:num/"